name: Java Code Lint and Format

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  lint_and_format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk maven

    - name: Lint Java code
      run: mvn checkstyle:check

    - name: Format Java code
      run: mvn com.google.cloud.tools:jib-maven-plugin:build-format

    - name: Commit changes (if any)
      run: |
        git diff --exit-code || (git config --global user.email "github-actions@github.com" && git config --global user.name "GitHub Actions" && git commit -am "Auto-format code" && git push)
